version: "3.9"

services:
  app:
    build: .
    image: fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    environment:
      API_V1_STR: "/api/v1"
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432"
    volumes:
      # map "folder" with WORKDIR/"folder" for auto reload if changes in local src
      - .:/code
    # command: uvicorn --host=0.0.0.0 --reload app.main:app

  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
