"""User: remove email

Revision ID: f4a4ec41b6c0
Revises: 9db173e86431
Create Date: 2021-08-31 17:38:43.152433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a4ec41b6c0'
down_revision = '9db173e86431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
